# example workflow for Black Duck SCA scans using the Black Duck Security Scan Action
# https://github.com/marketplace/actions/black-duck-security-scan
name: bd-self-hosted-action
on:
  push:
    branches: [ main, master, develop, stage, release ]
  pull_request:
    branches: [ main, master, develop, stage, release ]
  workflow_dispatch:
jobs:
  blackduck:
    runs-on: self-hosted
    steps:
    - name: Checkout Source
      uses: actions/checkout@v4
    - name: Maven Build
      run: mvn -B -DskipTests package
    - name: Black Duck SCA Scan
      uses: blackduck-inc/black-duck-security-scan@v2.0.0
      env:
        DETECT_PROJECT_NAME: ${{ github.event.repository.name }}
        NODE_TLS_REJECT_UNAUTHORIZED: 0
        BLACKDUCK_TRUST_CERT: true
      with:
        blackducksca_url: ${{ vars.BLACKDUCKSCA_URL }}
        blackducksca_token: ${{ secrets.BLACKDUCKSCA_TOKEN }}
        blackducksca_scan_failure_severities: 'BLOCKER'
        blackducksca_fixpr_enabled: true
        blackducksca_prComment_enabled: true
        github_token: ${{ secrets.GITHUB_TOKEN }}
#        blackducksca_reports_sarif_create: true
#        blackducksca_upload_sarif_report: true
        # include_diagnostics: true
#    - name: Save Logs
#      if: always()
#      uses: actions/upload-artifact@v4
#      with:
#        name: bridge-logs
#        path: ${{ github.workspace }}/.bridge
#        include-hidden-files: true
